name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'tsconfig.json'
      - 'next.config.js'
      - '.eslintrc.js'
      - '.prettierrc'
  pull_request:
    branches: [main, develop]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'tsconfig.json'
      - 'next.config.js'
      - '.eslintrc.js'
      - '.prettierrc'

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Run Prettier check
        run: pnpm format:check

      - name: Run ESLint check
        run: pnpm lint

      - name: Run TypeScript type check
        run: pnpm type-check

      - name: Build Next.js app
        run: pnpm build
        env:
          CI: true

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: .next/**
          retention-days: 7

  # deploy-preview:
  #   runs-on: ubuntu-latest
  #   needs: quality-checks
  #   if: github.event_name == 'pull_request'

  #   steps:
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: build-files
  #         path: .next/

  #     - name: Deploy Preview
  #       run: echo "Preview deployment would be triggered here"
  #       # Add your preview deployment logic here

  # deploy-production:
  #   runs-on: ubuntu-latest
  #   needs: quality-checks
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'

  #   steps:
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: build-files
  #         path: .next/

  #     - name: Deploy to Production
  #       run: echo "Production deployment would be triggered here"
  #       # Add your production deployment logic here
